version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asd

  backend:
    build: ./backend
    environment:
      FRONT_URL: http://localhost:5000
      DB_USERNAME: postgres
      DB_PASSWORD: asd
      DB_HOST: postgres
    expose:
      - 8000
    ports:
      - 8000:8000
    command: npm start
    restart: always
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    environment:
      API_URL: http://localhost:8000 
    expose:
      - 5000
    ports:
      - 5000:5000
    command: npm start
